# Project info
site_name: AI on Power - Level 3
site_description: AI on Power - Level 3 course
site_author: Deepak C Shetty (deepakcshetty@in.ibm.com)
copyright: Copyright &copy; 2024 IBM

# Repository
repo_name: IBM/AI-on-Power-Level3
#repo_url: https://github.com/IBM/SalesEnablement-L3-test-repo2
#edit_uri: edit/master/docs
docs_dir: docs

theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: "Switch to light mode"

plugins:
    - mkdocs-video:
        is_video: True
        video_autoplay: False
    - macros
    - search
    - glightbox

markdown_extensions:
  - toc:
     permalink: true
     toc_depth: 3
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences  
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets  
  - pymdownx.keys
  - attr_list
  - md_in_html

nav:
  - Introduction: 'index.md'
  - Pre-requisites: 'pre-req.md'
  - Lab setup instructions: 'lab-setup.md'
  - Lab1 - Deploy a LLM on Power10:
    - 'Lab Overview': 'Lab1/lab1-overview.md'
    - 'Hands-on guide': 'Lab1/lab1-hands-on-guide.md'
  - Lab2 - Deploy RAG on Power10:
    - 'Lab Overview': 'Lab2/lab2-overview.md'
    - 'Hands-on guide': 'Lab2/lab2-hands-on-guide.md'
  - Lab3 - Query DB using NL on Power10:
    - 'Lab Overview': 'Lab3/lab3-overview.md'
    - 'Hands-on guide': 'Lab3/lab3-hands-on-guide.md'
  - Credits

extra:
  generator: false
  supportEmail: "deepakcshetty@in.ibm.com"
  supportSlack: 
    name: "#cloud-platform-demo-feedback"
    url: "https://ibm-technology-sales.slack.com/archives/C03PQ47KRQE"
  learningplan:
    name: "IBM Power Virtual Server for Technical Sales - Level 3"
    url: "https://yourlearning.ibm.com/activity/PLAN-7D757C8B58E7"
  offering:
    name: "IBM Power Virtual Server"
  guide:
    name: "IBM Power Virtual Server - Level 3 Demonstration Guide"
    url: "https://ibm.github.io/SalesEnablement-PowerVS-L3/"
  tz_environment:
    name: "IBM Power Virtual Server - Sales Enablment L3"
    url: "https://techzone.ibm.com/my/reservations"
  account: "2305900 - ITZ - ADHOC03"
  powerVS:
    serviceInstanceName: "PowerVS-L3-2024"
    serviceInstanceRG: "PowerVS-L3"
    serviceInstanceLocation: "WDC07"
    placementGroup1: "GroupTogether"
    placementGroup2: "GroupApart"
    sshKey: "PowerVS-key"
    privateSubnet: "private-powervs-2024"
    privateSubnetCIDR: "192.168.100.0/24"
    privateSubnetGW: "192.168.100.15"
    privateSubnetDNS: "127.0.0.1"
    publicSubnet: "public-192_168_222_192-29-VLAN_2056
"
    monitoringInstance: "PowerVS-L3-Monitoring"
    atInstance: "AT-PowerVS-L3"
  aixServer1:
    name: "AIX-VM"
    privateIP: "192.168.100.112"
    publicIP: "150.239.207.227"
    additionalVolumeName: "aix-av1"
  linuxServer1:
    name: "Linux-VM"
    privateIP: "192.168.100.173"
    publicIP: "150.239.207.226"
    additionalVolumeName: "linux-av1"
  ibmiServer1:
    name: "IBMi-VM"
    privateIP: "192.168.100.157"
    publicIP: "150.239.207.228"
    additionalVolumeName: "ibmi-av1"
