# Project info
site_name: AI on Power - Level 3
site_description: AI on Power - Level 3 course
site_author: Deepak C Shetty, Learning Content Developer, IBM Power
copyright: Copyright &copy; 2024 IBM

# Repository
repo_name: IBM/AI-on-Power-Level3
#repo_url: https://github.com/IBM/SalesEnablement-L3-test-repo2
#edit_uri: edit/master/docs
docs_dir: docs

theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: "Switch to light mode"

plugins:
    - mkdocs-video:
        is_video: True
        video_autoplay: False
    - macros
    - search
    - glightbox
    - print-site:
        add_to_navigation: true
        print_page_title: 'Print Course'
        add_print_site_banner: true
        print_site_banner_template: docs/assets/templates/print_site_banner.tpl
        # Table of contents
        add_table_of_contents: true
        toc_title: 'Table of Contents'
        toc_depth: 6
        # Content-related
        add_full_urls: false
        enumerate_headings: false
        enumerate_figures: true
        add_cover_page: true
        cover_page_template: ""
        path_to_pdf: ""
        include_css: true
        enabled: true
        exclude:
          - helpful-tips.md

markdown_extensions:
  - toc:
     permalink: true
     toc_depth: 3
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences  
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets  
  - pymdownx.keys
  - attr_list
  - md_in_html

nav:
  - Getting Started: helpful-tips.md
  - Introduction: 'index.md'
  - Pre-requisites: 'pre-req.md'
  - Lab setup instructions: 'lab-setup.md'
  - Lab1 - Deploy a LLM on Power10:
    - 'Lab Education': 'Lab1/lab1-overview.md'
    - 'Hands-on guide': 'Lab1/lab1-hands-on-guide.md'
  - Lab2 - Deploy RAG on Power10:
    - 'Lab Education': 'Lab2/lab2-overview.md'
    - 'Hands-on guide': 'Lab2/lab2-hands-on-guide.md'
  - Lab3 - Deploy code LLM on Power10:
    - 'Lab Education': 'Lab3/lab3-overview.md'
    - 'Hands-on guide': 'Lab3/lab3-hands-on-guide.md'
  - Additional resources: resources.md
  - Credits: credits.md
  - Support: support.md

extra:
  generator: false
  supportEmail: "deepakcshetty@in.ibm.com"

